name: CI/CD Pipeline for Egolya Backend

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - dev
      - master

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run tests
  #       run: npm test

  #     - name: Run linter
  #       run: npm run lint
  #       if: always()

  deploy:
    # needs: test  # ← désactivé car job test est commenté
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare target directory on Cotanbo
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.COTANBO_HOST }}
          username: ${{ secrets.COTANBO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /app/egolya-backend

      - name: Sync code to Cotanbo
        run: |
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'node_modules' \
            ./ ${{ secrets.COTANBO_USERNAME }}@${{ secrets.COTANBO_HOST }}:/app/egolya-backend

      - name: Deploy with Docker Compose on Cotanbo
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.COTANBO_HOST }}
          username: ${{ secrets.COTANBO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /app/egolya-backend
            docker-compose down || true
            docker-compose up --build -d
