name: CI/CD Pipeline for Egolya Backend

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare target directory on Cotanbo
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.COTANBO_HOST }}
          username: ${{ secrets.COTANBO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /home/softengine/egolya-backend

      - name: Sync code to Cotanbo
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.COTANBO_HOST }} >> ~/.ssh/known_hosts
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'node_modules' \
            ./ ${{ secrets.COTANBO_USERNAME }}@${{ secrets.COTANBO_HOST }}:/home/softengine/egolya-backend

      - name: Create .env file on Cotanbo
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.COTANBO_HOST }}
          username: ${{ secrets.COTANBO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "${{ secrets.ENV_FILE }}" > /home/softengine/egolya-backend/.env

      - name: Deploy with Docker Compose on Cotanbo
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.COTANBO_HOST }}
          username: ${{ secrets.COTANBO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/softengine/egolya-backend
            docker-compose down || true
            docker-compose up --build -d
